stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
      - src/data_collection.py
      - params.yaml
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
      - params.yaml
    outs:
      - data/processed

  feature_selection:
    cmd: python src/feature_selection.py
    deps:
      - src/feature_selection.py
      - data/processed
      - params.yaml
    outs:
      - data/features

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - data/features
      - params.yaml
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - models/model.pkl
      - data/features
      - params.yaml
    outs:
      - reports/metrics.json
