seed: 42

data:
  dataset: "sklearn_digits"
  output_dir: "data/raw"
  num_images: 1000

processing:
  test_size: 0.2
  random_state: 42


features:
  variance_threshold: 0.0001

training:
  model_type: "mlp"
  hidden_layer_sizes: [128, 64]
  activation: "relu"
  solver: "adam"
  learning_rate_init: 0.001
  max_iter: 500
  batch_size: 32
  random_state: 42
  alpha: 0.001

evaluation:
  report_dir: "reports"
  save_confusion_matrix: true
